### ISSUE TITLE
hard crash if all gbars in a compartment are zero

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#174]
should throw an error instead

**Comment by sg-s** [comment]
this is because there are some unsafe divisions in the Crank-Nicholson scheme, so it only affects multi-compartment neurons

**Comment by alec-hoyland** [comment]
Should conductance/synapses check to see if gbar/gmax is zero before attempting to integrate. Presumably, it would be faster if this was done at the beginning of each simulation, rather than at each time step. I also imagine that this might be desirable to disable or work differently under some conditions (e.g. during a homeostasis/calcium integration scheme).

```c++
if (cond->gbar == 0) {
// return 0 for the current and exit
}

**Comment by sg-s** [comment]
I'm not sure where this bug comes from; all I know is that it doesn't exist in single-compartment neurons (because there is a check as you described, at every time point)

**Comment by sg-s** [comment]
this has been fixed.
