### ISSUE TITLE
Add synapses from these papers (possibily just one model)

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#203]
- [ ] https://www.nature.com/articles/382807a0
- [ ] http://www.pnas.org/content/94/2/719

**Comment by alec-hoyland** [comment]
Where is the current equation? I see the kinetic equations that determine the fraction of resources, and there is an equation for computing the membrane potential `tau * dV/dt = -V + R*I_syn(t)` but there's no equation for the synaptic current. I'm not sure how you use the EPSC equation given unless you have an *a priori* presynaptic spike train.

**Comment by sg-s** [comment]
no idea -- i just want more synapses in the paper than just the two from prinz.

**Comment by alec-hoyland** [comment]
I think this method requires an *a priori* spike train. This is true for the alpha synapse model as well 

`I_syn(t - t0) = gbar * (t - t0)/tau * exp(-(t - t0  - tau)/tau)*(Vm - E_syn)`

where `t0` is the onset of the incident spike.

**Comment by alec-hoyland** [comment]
I did some of my own research today and talked to Noah. Neither of us can find a paper that actually implements an alpha synapse (or other spike-train-mediated model) in a conductance-based network model.

C Borgers in _An Introduction to Modeling Neuronal Dynamics Ch. 20_ describes a series of models (nearly-instantaneous rise, gradual rise, Jahr-Stevens). If we wanted a model with actual instantaneous rise, we would need a prefactor that's essential just a Heaviside function `H(V_pre - V_th)`. These models all rely on integrating a state variable `s` rather than attempting to only reproduce EPSPs from a known (presynaptic) spike train.

**Comment by sg-s** [comment]
there are a bunch of textbooks on my desk -- look at the ones that are not Dayan&Abbott
