### ISSUE TITLE
maybe there's a better way to integrate the voltage

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#211]
right now, the conductance dynamics depend on the voltage at the previous time step, but the affevt the voltage based on their dynamics in this time step. 

i think the more correct thing to do is to make them update `V_inf`, `gE` etc based on the `m` and `h` in the previous time step.

this is as simple as updating `V_inf` and then integrating the conductances.

**Comment by alec-hoyland** [comment]
This should work, because `V_inf` relies on `g, E, ...` at time `t` so integrating `V` doesn't rely on integrating `g` (that is, no dependence on `g(t + dt)`). I don't know if it would get an appreciable speed boost, though should help with readability.

**Comment by alec-hoyland** [comment]
On the topic of integrating the voltage, exponential euler has the disadvantage of being numerically unstable. Do you think that this is a problem that we need to address (e.g. provide an rk4 alternative)?

**Comment by alec-hoyland** [comment]
I generally agree with you, though Noah and Leandro believe that it is unstable, which is why I want to check more thoroughly. Here are the results for 27 models found through the `reprinz` method where error is computed through the LeMasson matrix method (same as benchmark figure).

![untitled](https://user-images.githubusercontent.com/30243182/43332581-b5569c54-9196-11e8-99bd-f921c660bf9e.png)

**Comment by sg-s** [comment]
so not even 1 out of 27 models explodes as you vary time step? i'd call that a success. i imagine you've also looked at the time traces at `dt=1ms` to verify that it kinda looks the same?
