### ISSUE TITLE
Order of x.Children

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#296]
**x.Children** now places the compartments in alphabetical order. Can it be changed so that it is in the original order of addition?

**Comment by sg-s** [comment]
no, because we need a deterministic way of traversing a tree. sorting `Children` alphabetically ensures that the same tree will have the same MD5 hash, which is crucial for correct compilation, auditability, etc. 

I can't think of any application where I would need to know the order in which I added components.

**Comment by luadam4c** [comment]
It's a little confusing to the user.
I almost injected currents in the wrong compartment, because I added soma before dendrite, and then placed the current injections in the first column.

Perhaps make the fact that the columns or I_ext and V_clamp are sorted alphabetically according to the compartment names clear in the documentation
