### ISSUE TITLE
Documentation doesn't show up in MATLAB

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#345]
MATLAB is getting bamboozled by our clever documentation tricks, and isn't displaying the documentation inside the command window. It would be nice to be able to run the `help` command in MATLAB and see the Markdown at the beginning of each xolotl file.

```matlab
>> help xolotl.integrate
 {

>> 
```

**Comment by alec-hoyland** [comment]
https://www.mathworks.com/help/matlab/matlab_prog/display-custom-documentation.html

**Comment by sg-s** [comment]
OK, here's what I know:

* matlab's help command will print all comments that start with a %
* block comments are not supported. that's why it shows only a `{`
* we use block comments because it makes markdown parsing easier, but we could switch to the other form. 
* if we do so, then the "help" text in every method has to switched from block comment to inline comment
* in addition, there needs to be a minor tweak in the python script that assembles the documentation, but this is easy to do. 

i agree that typing `help xolotl.integrate` would be useful. in order to get this working, we need to do the things listed above. thoughts?

**Comment by alec-hoyland** [comment]
Theoretically, there are other ways to do this, involving writing custom XML files for MATLAB, but that could basically be the Platonic ideal for _more trouble than it's worth_. I think this is the best fix, since it is straightforward. I'll make a new branch and do the unsavory task of adding % before each line.

**Comment by alec-hoyland** [comment]
https://github.com/sg-s/xolotl/tree/matlab-help

**Comment by sg-s** [comment]
xolotl has a new method (loadobj), so you probably want to pull from master

**Comment by sg-s** [comment]
i hope you're not doing this manually -- write a python script to do this automatically

**Comment by alec-hoyland** [comment]
I did it using tools built into Atom -- slower than using a script but faster than writing a script just to use it once. All xolotl and xtools methods/functions are fixed. I have not touched the `make_docs.py` script.

**Comment by alec-hoyland** [comment]
PR #347

**Comment by alec-hoyland** [comment]
Fixed in PR #347
