### ISSUE TITLE
xolotl should prevent compartment from being added that have 

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#37]
names of classes in C++ code -- like `CaS` or `Glutamatergic`

**Comment by sg-s** [comment]
also compartments shouldn't have `.` or `/` in their names etc

**Comment by sg-s** [comment]
but how do we get a list of all forbidden names?

**Comment by alec-hoyland** [comment]
The brute-force method would be to dir in xolotl/c++/conductances then for
each subfolder get the name, then for each name, get the names of contained
files, get unique names, and add them to a banned name list.

Of course this is only necessary if a) there's not a more elegant method
and b) xolotl would have issues with x.CaS.CaS being a conductance.
Otherwise, we can trust people to not be idiots...

**Comment by sg-s** [comment]
fixed. I used an already existing function in cpplab
