### ISSUE TITLE
Non-linear driving forces for individual currents

### ISSUE THREAD

**Issue by JRS92** [sg-s/xolotl#484]
I would like to try using non-linear driving forces for some of my currents. It looks like I would need to change getCurrent in the conductance class, but this would change all conductances. Am I correct in assuming this and if so how would you recommend implementing this? Thanks.

**Comment by sg-s** [comment]
Hi, I think it should be possible to get what you want without changing any of the core code. 

There are multiple ways to do this:

## 1. Rewrite your equation so that it "looks" linear

Even if you have a non-linear equation for your current, it can be rewritten to appear so that xolotl can work with it. For example, see how it's done [here](https://github.com/sg-s/xolotl/blob/5a3a2b97190a0b8e0b19358163aad43ba37783f4/c%2B%2B/conductances/destexhe98/CaT.hpp#L120)

## 2. Use the `use_current` flag

xolotl has a `use_current` flag:

x.use_current = 1;

will tell it to integrate the model by explicitly calculating the currents. Then your conductance can do whatever it wants, including using non-linear models for current. 

If any of this is too complex, let me know what channel you want to model and I can write that for you fairly quickly

**Comment by JRS92** [comment]
Thanks, I will email you a conductance I have been using with xfit. It is basically just modified GenericNaVLike.hpp . I did not bother to change the defaults. I would like to use GHK driving forces as in [Clay 2000](https://link.springer.com/article/10.1007/s002490000091). I'm pretty helpless with C++ unfortunately. I will try to copy your example but if this is trivial for you, help would be appreciated! Thanks.

**Comment by sg-s** [comment]
Hi, I added a new channel (clay00/Kd2) to the project. 

You can test drive it using:

```
x = xolotl.examples.BurstingNeuron('prefix','liu'); x.AB.add('clay00/Kd2','gbar',1e-4, 'Erev',-80); 
x.AB.Kd.gbar = 0; 
x.plot
```

and you should get something like this:


![Screen Shot 2020-02-24 at 4 52 21 PM](https://user-images.githubusercontent.com/6005346/75194411-0efc2200-5726-11ea-9bfc-9867b6d7cd2c.png)

Here's [a direct link](https://github.com/sg-s/xolotl/blob/master/c%2B%2B/conductances/clay00/Kd2.hpp) to the new conductance so you can download them and drop it somewhere on your path so that cpplab can find it

Here's the relevant portion of the code that linearizes the non-linear current equation:

```
void Kd2::integrate(double V_, double Ca_){


    // Equation 1  can be re-written to be in the form
    // I = gV - gE
    // where E = 0. Then, g is given by
    // a dynamically changing variable 

    // Note that equation 1 is wrong -- it's not qV-EK, it's
    // q(V-EK)
    g = gbar*(exp((V_-Erev)/25) - 1)/(exp(V_/25) - 1);

}

```

**Comment by JRS92** [comment]
Thanks for the help and good catch on the typo! I guess I need to call my m_inf, tau_m functions  in integrate() as well? Otherwise it's basically a non-linear leak channel.

**Comment by JRS92** [comment]
I made getCurrent a virtual function in the conductance class and redefined it in the channel I wanted to use this for, swapping out (V-E) for (exp((V_-Erev)/25) - 1)/(exp(V_/25) - 1). This seems to work.

**Comment by alec-hoyland** [comment]
Yes, that should work just fine. Off the top of my head, I don't see any reason why `getCurrent` shouldn't be virtual so that each conductance can define its own method if needed. @sg-s thoughts?

**Comment by sg-s** [comment]
Good point. Why isn't `getCurrent` virtual?

**Comment by sg-s** [comment]
Hope this fixed your issue, closing for now. Please reopen if otherwise
